sudo: required
language: csharp
mono: none
dotnet: 6.0

branches:
  except:
    # this is required to avoid building tags.
    - /^v?\d+\.\d+\.\d+(\w*\W*)*$/
script:
  # the library (so you can import an use it on cf4dotnet projects)
  - sed -i -e "s/000/${TRAVIS_BUILD_NUMBER^^}/g" $TRAVIS_BUILD_DIR/src/Cloudformation4dotNET.Library.csproj
  - dotnet pack $TRAVIS_BUILD_DIR/src -c release -o $TRAVIS_BUILD_DIR/artifacts
deploy:
  - provider: script
    skip_cleanup: true
    script: dotnet nuget push $TRAVIS_BUILD_DIR/artifacts/NachoColl.Cloudformation4dotNET.Library.*.nupkg --api-key $NUGET_APIKEY --source https://www.nuget.org
    on: master 
